version: "3.9"
   
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=SuperSecret

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
